// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("germanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("indonesianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LearningLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.VocabEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Backside")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BacksideAfterNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("BacksideBeforeNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frontside")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontsideAfterNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontsideBeforeNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Languagekey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("hasCopyright")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vocabs");
                });

            modelBuilder.Entity("Backend.Models.VocabProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GreenStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "VocabId")
                        .IsUnique();

                    b.ToTable("VocabProgress");
                });

            modelBuilder.Entity("Backend.Models.VocabProgress", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("VocabProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("VocabProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
